import Mathlib

/-!
# Numerical semigroups

A *numerical semigroup* is a subset `S ⊆ ℕ` that contains `0`, is closed under
addition and whose complement in `ℕ` is finite.  Every numerical semigroup is
generated by a finite family of positive generators
`n₁ < n₂ < ⋯ < n_k` with `gcd (n₁, …, n_k) = 1`:  it is the set of all
non-negative integer combinations of the generators.

In this file we define the (additive) submonoid of `ℕ` generated by a finite
family of generators, together with its membership predicate.

We model a *finite list* of `k` generators as a function `n : Fin k → ℕ`; this
is a length-`k` tuple `(n 0, n 1, …, n (k-1))`.
-/

namespace NumSemigroups

open scoped BigOperators

/-- The numerical semigroup generated by a finite family of generators
`n : Fin k → ℕ`.  It is the set of all elements of `ℕ` that can be written as a
non-negative integer combination `∑ i, a i * n i` of the generators. -/
def Generated {k : ℕ} (n : Fin k → ℕ) : Set ℕ :=
  {s : ℕ | ∃ a : Fin k → ℕ, (∑ i, a i * n i) = s}

/-- `0` belongs to every generated numerical semigroup (take all coefficients
zero). -/
theorem zero_mem_Generated {k : ℕ} (n : Fin k → ℕ) : (0 : ℕ) ∈ Generated n := by
  refine ⟨fun _ => 0, ?_⟩
  simp

/-- A generated numerical semigroup is closed under addition. -/
theorem add_mem_Generated {k : ℕ} (n : Fin k → ℕ) {s t : ℕ}
    (hs : s ∈ Generated n) (ht : t ∈ Generated n) : s + t ∈ Generated n := by
  obtain ⟨a, ha⟩ := hs
  obtain ⟨b, hb⟩ := ht
  refine ⟨fun i => a i + b i, ?_⟩
  simp only [add_mul, Finset.sum_add_distrib, ha, hb]

end NumSemigroups
