import NumSemigroups.Factorization

/-!
# Elasticity of numerical semigroups

For a nonzero element `s` of a numerical semigroup, the *elasticity* of `s` is
`ρ(s) = max L(s) / min L(s)`, where `L(s)` is the length set of `s`.  The
*elasticity of the semigroup* `S`, `ρ(S)`, is the supremum of `ρ(s)` over all
nonzero `s ∈ S`.

## Main result

`elasticity_eq`: for `S = ⟨n₀, …, n_{k-1}⟩` generated by a strictly increasing
family of positive generators (with at least two generators), the elasticity of
`S` equals `n_max / n_min = n (Fin.last …) / n 0`.

We index a family with (at least) two generators as `n : Fin (d + 2) → ℕ`, so
the smallest generator is `n 0` and the largest is `n (Fin.last (d + 1))`.
-/

namespace NumSemigroups

open scoped BigOperators

/-- The smallest length among the factorizations of `s`. -/
noncomputable def minLen {k : ℕ} (n : Fin k → ℕ) (s : ℕ) : ℕ := sInf (lengthSet n s)

/-- The largest length among the factorizations of `s`. -/
noncomputable def maxLen {k : ℕ} (n : Fin k → ℕ) (s : ℕ) : ℕ := sSup (lengthSet n s)

/-- The elasticity of an element `s`, `ρ(s) = max L(s) / min L(s)`, as a rational
number. -/
noncomputable def rho {k : ℕ} (n : Fin k → ℕ) (s : ℕ) : ℚ :=
  (maxLen n s : ℚ) / (minLen n s : ℚ)

/-- The set of elasticities of nonzero elements of the generated semigroup,
viewed inside `ℝ`. -/
def elasticitySet {d : ℕ} (n : Fin (d + 2) → ℕ) : Set ℝ :=
  {r : ℝ | ∃ s : ℕ, s ∈ Generated n ∧ s ≠ 0 ∧ r = ((rho n s : ℚ) : ℝ)}

/-- The elasticity of the semigroup `S`, `ρ(S)`, the supremum of `ρ(s)` over all
nonzero `s ∈ S`. -/
noncomputable def elasticity {d : ℕ} (n : Fin (d + 2) → ℕ) : ℝ :=
  sSup (elasticitySet n)

section Bounds

variable {d : ℕ} (n : Fin (d + 2) → ℕ)

/-- Every generator is at least the smallest one, `n 0`. -/
theorem le_of_min (hmono : StrictMono n) (i : Fin (d + 2)) : n 0 ≤ n i :=
  hmono.monotone (Fin.zero_le i)

/-- Every generator is at most the largest one, `n (Fin.last (d + 1))`. -/
theorem le_of_max (hmono : StrictMono n) (i : Fin (d + 2)) :
    n i ≤ n (Fin.last (d + 1)) :=
  hmono.monotone (Fin.le_last i)

/-
A factorization using `L` generators has value at least `L * n 0`.
-/
theorem sum_min_le (hmono : StrictMono n) (a : Fin (d + 2) → ℕ) :
    (∑ i, a i) * n 0 ≤ ∑ i, a i * n i := by
  simpa only [ Finset.sum_mul _ _ _ ] using Finset.sum_le_sum fun i _ => Nat.mul_le_mul_left _ ( hmono.monotone ( Nat.zero_le _ ) )

/-
A factorization using `L` generators has value at most `L * n_max`.
-/
theorem sum_le_max (hmono : StrictMono n) (a : Fin (d + 2) → ℕ) :
    (∑ i, a i * n i) ≤ (∑ i, a i) * n (Fin.last (d + 1)) := by
  simpa only [ Finset.sum_mul _ _ _ ] using Finset.sum_le_sum fun i _ => mul_le_mul_of_nonneg_left ( hmono.monotone ( Fin.le_last _ ) ) ( Nat.zero_le _ )

/-
Any length `L ∈ L(s)` satisfies `L * n 0 ≤ s`.
-/
theorem length_mul_min_le (hmono : StrictMono n) {s L : ℕ}
    (hL : L ∈ lengthSet n s) : L * n 0 ≤ s := by
  obtain ⟨ a, ha, rfl ⟩ := hL;
  exact ha ▸ sum_min_le n hmono a

/-
Any length `L ∈ L(s)` satisfies `s ≤ L * n_max`.
-/
theorem le_length_mul_max (hmono : StrictMono n) {s L : ℕ}
    (hL : L ∈ lengthSet n s) : s ≤ L * n (Fin.last (d + 1)) := by
  obtain ⟨ a, ha, rfl ⟩ := hL;
  exact ha ▸ sum_le_max n hmono a

/-
The length set of any element is bounded above (each length is `≤ s`).
-/
theorem lengthSet_bddAbove (hmono : StrictMono n) (hpos : 0 < n 0) (s : ℕ) :
    BddAbove (lengthSet n s) := by
  exact ⟨ s, fun L hL => by rcases hL with ⟨ a, ha, rfl ⟩ ; exact Nat.le_trans ( show ∑ x : Fin ( d + 2 ), a x ≤ s from by nlinarith [ show ∑ x : Fin ( d + 2 ), a x * n x = s from ha, show ∑ x : Fin ( d + 2 ), a x * n x ≥ ∑ x : Fin ( d + 2 ), a x from Finset.sum_le_sum fun i _ => by nlinarith [ hmono.monotone <| show 0 ≤ i from Nat.zero_le i ] ] ) ( by linarith ) ⟩

end Bounds

section Special

variable {d : ℕ} (n : Fin (d + 2) → ℕ)

/-- The distinguished element `s₀ = n₀ · n_max` on which the extremal ratio is
attained. -/
private def sSpecial : ℕ := n 0 * n (Fin.last (d + 1))

/-
`s₀ = n 0 * n_max` belongs to the semigroup and is nonzero.
-/
theorem sSpecial_mem (hpos : 0 < n 0) (hmono : StrictMono n) :
    sSpecial n ∈ Generated n ∧ sSpecial n ≠ 0 := by
  refine' ⟨ _, mul_ne_zero hpos.ne' ( ne_of_gt ( hpos.trans_le ( hmono.monotone ( Nat.zero_le _ ) ) ) ) ⟩;
  use fun i => if i = 0 then n (Fin.last (d + 1)) else 0;
  simp +decide [ sSpecial ];
  ring

/-
The maximal length of `s₀` is `n_max`: use `n_max` copies of the generator
`n 0`.
-/
theorem maxLen_sSpecial (hpos : 0 < n 0) (hmono : StrictMono n) :
    maxLen n (sSpecial n) = n (Fin.last (d + 1)) := by
  refine' csSup_eq_of_forall_le_of_forall_lt_exists_gt _ _ _ <;> norm_num [ sSpecial ];
  · refine' ⟨ _, ⟨ fun i => if i = 0 then n ( Fin.last ( d + 1 ) ) else 0, _, rfl ⟩ ⟩ ; simp +decide [ IsFactorization ];
    ring;
  · rintro L ⟨ a, ha₁, rfl ⟩;
    have := length_mul_min_le n hmono ⟨ a, ha₁, rfl ⟩;
    nlinarith;
  · intro w hw; use n ( Fin.last ( d + 1 ) ) ; simp_all +decide [ lengthSet ] ;
    use fun i => if i = 0 then n ( Fin.last ( d + 1 ) ) else 0 ; simp_all +decide [ IsFactorization, length ] ; ring;

/-
The minimal length of `s₀` is `n 0`: use `n 0` copies of the generator
`n_max`.
-/
theorem minLen_sSpecial (hpos : 0 < n 0) (hmono : StrictMono n) :
    minLen n (sSpecial n) = n 0 := by
  refine' le_antisymm ( csInf_le _ _ ) ( le_csInf _ _ );
  · exact ⟨ 0, fun x hx => Nat.zero_le _ ⟩;
  · use fun i => if i = Fin.last ( d + 1 ) then n 0 else 0;
    simp +decide [ IsFactorization, length, sSpecial ];
  · exact ⟨ _, ⟨ fun i => if i = Fin.last _ then n 0 else 0, by unfold IsFactorization sSpecial; simp +decide, rfl ⟩ ⟩;
  · intro b hb
    obtain ⟨a, ha⟩ := hb;
    have h_le : (∑ i, a i) * n (Fin.last (d + 1)) ≥ sSpecial n := by
      exact ha.1.symm ▸ sum_le_max n hmono a;
    unfold sSpecial at *;
    nlinarith [ show 0 < n ( Fin.last ( d + 1 ) ) from lt_of_lt_of_le hpos ( hmono.monotone ( Nat.zero_le _ ) ), ha.2, show ∑ i, a i = b from ha.2 ]

/-
The elasticity of `s₀` is exactly `n_max / n 0`.
-/
theorem rho_sSpecial (hpos : 0 < n 0) (hmono : StrictMono n) :
    rho n (sSpecial n) = (n (Fin.last (d + 1)) : ℚ) / (n 0 : ℚ) := by
  unfold rho
  rw [maxLen_sSpecial n hpos hmono, minLen_sSpecial n hpos hmono]

end Special

section Main

variable {d : ℕ} (n : Fin (d + 2) → ℕ)

/-
The upper bound: for every nonzero `s ∈ S`, `ρ(s) ≤ n_max / n 0`.
-/
theorem rho_le (hpos : 0 < n 0) (hmono : StrictMono n) {s : ℕ}
    (hs : s ∈ Generated n) (hs0 : s ≠ 0) :
    rho n s ≤ (n (Fin.last (d + 1)) : ℚ) / (n 0 : ℚ) := by
  rw [ rho, div_le_div_iff₀ ] <;> norm_cast;
  · -- By definition of `maxLen` and `minLen`, we know that `maxLen n s ∈ lengthSet n s` and `minLen n s ∈ lengthSet n s`.
    obtain ⟨a_max, ha_max⟩ : ∃ a_max : Fin (d + 2) → ℕ, IsFactorization n s a_max ∧ length a_max = maxLen n s := by
      convert Nat.sSup_mem ?_;
      rotate_left;
      exact { L | ∃ a : Fin ( d + 2 ) → ℕ, IsFactorization n s a ∧ length a = L };
      · exact ⟨ _, ⟨ hs.choose, hs.choose_spec, rfl ⟩ ⟩;
      · exact ⟨ fun h => fun _ => h, fun h => h <| lengthSet_bddAbove n hmono hpos s ⟩
    obtain ⟨a_min, ha_min⟩ : ∃ a_min : Fin (d + 2) → ℕ, IsFactorization n s a_min ∧ length a_min = minLen n s := by
      exact Nat.sInf_mem ( show ( lengthSet n s ).Nonempty from by rw [ mem_Generated_iff_lengthSet_nonempty ] at hs; exact hs );
    simpa [Nat.mul_comm] using
      (length_mul_min_le n hmono ⟨a_max, ha_max.1, ha_max.2⟩ |>.trans
        (le_length_mul_max n hmono ⟨a_min, ha_min.1, ha_min.2⟩))
  · obtain ⟨ a, ha ⟩ := hs;
    contrapose! hs0;
    simp_all +decide [ minLen ];
    cases hs0 <;> simp_all +decide [ lengthSet ];
    · obtain ⟨ a, ha₁, ha₂ ⟩ := ‹_›; simp_all +decide [ IsFactorization, length ] ;
    · rename_i h; rw [ Set.eq_empty_iff_forall_notMem ] at h; specialize h ( ∑ i, a i ) ; simp_all +decide [ IsFactorization, length ] ;
      exact False.elim <| h a ha rfl

/-
`n_max / n 0` is the greatest elasticity, and it is attained.
-/
theorem isGreatest_elasticitySet (hpos : 0 < n 0) (hmono : StrictMono n) :
    IsGreatest (elasticitySet n)
      ((n (Fin.last (d + 1)) : ℝ) / (n 0 : ℝ)) := by
  refine' ⟨ _, _ ⟩;
  · use sSpecial n;
    convert sSpecial_mem n hpos hmono using 1;
    rw [ rho_sSpecial n hpos hmono ] ; norm_num [ hpos.ne', hmono.injective.eq_iff ];
  · rintro r ⟨ s, hs, hs0, rfl ⟩
    have hr : (rho n s : ℚ) ≤ (n (Fin.last (d + 1)) : ℚ) / (n 0 : ℚ) := by
      convert rho_le n hpos hmono hs hs0 using 1
    norm_cast at *;
    rw [ le_div_iff₀ ] at * <;> norm_cast at *

/-
**Flagship theorem.**  For a numerical semigroup `S = ⟨n₀, …, n_{k-1}⟩`
generated by a strictly increasing family of positive generators with `k ≥ 2`
generators, the elasticity of `S` equals `n_max / n_min`.
-/
theorem elasticity_eq (hpos : 0 < n 0) (hmono : StrictMono n) :
    elasticity n = (n (Fin.last (d + 1)) : ℝ) / (n 0 : ℝ) := by
  convert IsLUB.csSup_eq ( isGreatest_elasticitySet n hpos hmono |> IsGreatest.isLUB ) using 1;
  exact ⟨ fun h => fun _ => h, fun h => h <| by exact ⟨ _, ⟨ _, sSpecial_mem n hpos hmono |>.1, sSpecial_mem n hpos hmono |>.2, rfl ⟩ ⟩ ⟩

end Main

end NumSemigroups