import NumSemigroups.Defs

/-!
# Factorizations and length sets

For an element `s` of a numerical semigroup generated by `n : Fin k → ℕ`, a
*factorization* of `s` is a tuple of non-negative integers `a : Fin k → ℕ` with
`∑ i, a i * n i = s`.  Its *length* is `∑ i, a i`, and the *length set* `L(s)`
is the set of all lengths of factorizations of `s`.
-/

namespace NumSemigroups

open scoped BigOperators

/-- `a : Fin k → ℕ` is a factorization of `s` for the generators `n` when
`∑ i, a i * n i = s`. -/
def IsFactorization {k : ℕ} (n : Fin k → ℕ) (s : ℕ) (a : Fin k → ℕ) : Prop :=
  (∑ i, a i * n i) = s

/-- The length of a factorization is the total number of generators used,
`∑ i, a i`. -/
def length {k : ℕ} (a : Fin k → ℕ) : ℕ := ∑ i, a i

/-- The length set `L(s)`: the set of lengths of all factorizations of `s`. -/
def lengthSet {k : ℕ} (n : Fin k → ℕ) (s : ℕ) : Set ℕ :=
  {L : ℕ | ∃ a : Fin k → ℕ, IsFactorization n s a ∧ length a = L}

/-- `s` lies in the generated semigroup iff it has at least one factorization,
i.e. iff its length set is nonempty. -/
theorem mem_Generated_iff_lengthSet_nonempty {k : ℕ} (n : Fin k → ℕ) (s : ℕ) :
    s ∈ Generated n ↔ (lengthSet n s).Nonempty := by
  constructor
  · rintro ⟨a, ha⟩
    exact ⟨length a, a, ha, rfl⟩
  · rintro ⟨L, a, ha, _⟩
    exact ⟨a, ha⟩

end NumSemigroups
