import NumSemigroups.Basic

/- ═══════════════════════════════════════════════════════════════════
   PAPER 1 — Fibonacci numerical semigroups
   arXiv:math/0606717 (Marín, Ramírez Alfonsín, Revuelta)
   Theorem 1.1: g(F_i, F_{i+2}, F_{i+k}), with r = ⌊(F_i - 1)/F_k⌋.
   Two printed branches; branch 1 has two sub-conditions, so three
   cases below. Convention F_1 = F_2 = 1. The paper states NO worked
   numerical examples, so all instances are derived from the formula.
   ═══════════════════════════════════════════════════════════════════ -/

-- Case 1a: r = 0. Formula collapses to the 2-generator Sylvester value;
-- third generator is always redundant here. (i,k) = (5,5).
theorem fib_case1a_i5_k5 : frobeniusNumber [5, 13, 55] = 47 := by native_decide

-- Case 1a again, (i,k) = (3,6), smallest instance.
theorem fib_case1a_i3_k6 : frobeniusNumber [2, 5, 34] = 3 := by native_decide

-- Case 1b: r ≥ 1 and F_{k-2}·F_i < (F_i - r·F_k)·F_{i+2}. (i,k) = (5,3).
theorem fib_case1b_i5_k3 : frobeniusNumber [5, 13, 21] = 37 := by native_decide

-- Case 1b, second data point, (i,k) = (7,6).
theorem fib_case1b_i7_k6 : frobeniusNumber [13, 34, 233] = 356 := by native_decide

-- Case 2 ("otherwise"): r ≥ 1 and F_{k-2}·F_i ≥ (F_i - r·F_k)·F_{i+2}.
-- (11,6) is the SMALLEST instance of this case that exists — k=3,4,5 can
-- never reach it, and k=6 needs F_i ≡ 1 (mod 8), first hit at F_11 = 89.
theorem fib_case2_i11_k6 : frobeniusNumber [89, 233, 1597] = 17512 := by native_decide

-- Corollary 1.2 gives genus as a SINGLE formula with no case split, even
-- though F has two branches — worth an independent look. For (5,3):
-- N = ((F_i-1)(F_{i+2}-1) - r·F_{k-2}(2F_i - F_k(1+r)))/2 = (4·12 - 2(10-6))/2 = 20.
theorem fib_genus_i5_k3 : genusApery [5, 13, 21] = 20 := by native_decide


/- ═══════════════════════════════════════════════════════════════════
   PAPER 2 — Generalized Thabit numerical semigroups
   arXiv:1510.04801 (Kyunghwan Song)
   GT(n,k) generated by s_i = (2^k+1)·2^(n+i) - (2^k-1).
   F(GT(n,k)) splits into cases on how k relates to n.
   ═══════════════════════════════════════════════════════════════════ -/

-- Case n = 0 (Lemma 4.9): F = 2^k + 1. GT(0,3) = ⟨2,11⟩ (Example 3.8).
theorem thabit_n0 : frobeniusNumber [2, 11] = 9 := by native_decide

-- Case k = n ≥ 1 (Lemma 4.10). GT(2,2), generators from Theorem 3.6.
theorem thabit_kEqn : frobeniusNumber [17, 37, 77, 157, 317] = 337 := by native_decide

-- Case k = n - 1 (Corollary 4.12). GT(3,2), generators from Example 3.9.
theorem thabit_kEqnMinus1 :
    frobeniusNumber [37, 77, 157, 317, 637, 1277] = 1551 := by native_decide

-- Case 2 ≤ k < n, general (§4.2, Examples 4.14 / 4.18).
theorem thabit_kLtN_ex1 :
    frobeniusNumber [281, 569, 1145, 2297, 4601, 9209, 18425, 36857, 73721]
      = 81483 := by native_decide

-- Case 2 ≤ k < n, general (§4.2, Example 4.19).
theorem thabit_kLtN_ex2 :
    frobeniusNumber [1145, 2297, 4601, 9209, 18425, 36857, 73721, 147449,
      294905, 589817, 1179641] = 1325903 := by native_decide

-- Case n ≠ 0, k > n, k ≠ 2 (§4.3, Example 4.26).
theorem thabit_kGtN : frobeniusNumber [29, 65, 137, 281, 569] = 1095 := by native_decide

-- NOT COVERED: the paper's genuine exception case (n,k) = (1,2),
-- GT(1,2) = ⟨7,17,37⟩ — the source text never resolves it.


/- ═══════════════════════════════════════════════════════════════════
   PAPER 3 — Generalized repunit numerical semigroups
   arXiv:2306.10738 (Liu, Xin, Ye, Yin), "A Note on Generalized
   Repunit Numerical Semigroups". No mod-based case split — instead a
   strict hierarchy of three generality levels. Paper has NO worked
   numerical examples of its own; all instances constructed.
   ═══════════════════════════════════════════════════════════════════ -/

-- Case 1 (Theorem 3.5): general family a_i = b^i·a + (b^i-1)/(b-1)·d,
-- requires gcd(a,d)=1 and a ≥ k-1. Instance b=2, d=3, k=2, a=5.
theorem grepunit_thm35 : frobeniusNumber [5, 13, 29] = 37 := by native_decide

theorem grepunit_thm35_genus : genusApery [5, 13, 29] = 20 := by native_decide

-- Case 2 (Theorem 4.1): generalized-repunit specialization, k = n-1,
-- a = (b^n-1)/(b-1). F = (b^n + d - 1)(b^n-1)/(b-1) - d.
-- Instance b=2, n=3, d=3 → a=7.
theorem grepunit_thm41 : frobeniusNumber [7, 17, 37] = 67 := by native_decide

theorem grepunit_thm41_genus : genusApery [7, 17, 37] = 38 := by native_decide

-- Case 3 (Corollary 4.2): classical repunit sub-case, d = 1.
-- b=2, n=3 → ⟨7,15,31⟩. The F formula is correct: 7·8 - 1 = 55.
theorem grepunit_cor42_frobenius : frobeniusNumber [7, 15, 31] = 55 := by native_decide

/- ⚠ DISCREPANCY — Corollary 4.2's GENUS formula.
   As printed: g = (b^n/2)·((b^n-1)/(b-1) + n - 1), giving (8/2)(7+2) = 36.
   Correctly specializing the paper's OWN Theorem 4.1 genus formula at d=1
   gives (b^n/2)·(a + n - 2), i.e. (8/2)(7+1) = 32. The true genus is 32.
   The printed version is too large by exactly b^n/2, and is non-integral
   whenever b^n is odd (e.g. b=3,n=2 gives 22.5) — an immediate red flag,
   since genus must be an integer. Theorem 4.1 itself is fine; only the
   Corollary's specialization is wrong. -/
theorem grepunit_cor42_genus_TRUE : genusApery [7, 15, 31] = 32 := by native_decide


/- ═══════════════════════════════════════════════════════════════════
   PAPER 4 — Repunit numerical semigroups (Rosales–Branco–Torrão),
   Ramanujan J. 40 (2016) 323–334, doi:10.1007/s11139-015-9719-3
   BLOCKED: paywalled (Springer, $39.95, no preprint found). Abstract
   confirms closed forms for embedding dimension, Frobenius number,
   type, and genus, but the formulas themselves are behind the paywall.
   No theorems can be written for this paper yet.
   ═══════════════════════════════════════════════════════════════════ -/


/- ═══════════════════════════════════════════════════════════════════
   PAPER 5 — Semigroups from a linear recurrence
   arXiv:2111.04899 (Arias, Borja, Rhenals), "The Frobenius problem for
   numerical semigroups generated by tails of sequences of the form
   c·a^n - d". Repunits R_t = (a^t - 1)/(a - 1). λ = gcd(S_n).
   ═══════════════════════════════════════════════════════════════════ -/

-- Master theorem (Corollary 5.1) via Example 5.2(1): x_n = a^n - 1,
-- a=3, n=3 → F = a^n·R_n - 1 = 27·13 - 1 = 350.
theorem linrec_cor51 : frobeniusNumber [13, 40, 121] = 350 := by native_decide

/- ⚠ DISCREPANCY — Example 5.2(2), family x_n = 5·3^n - 1 (λ=2).
   The paper's derivation of max Ap(S_n, s_0) = 2s_n + s_{n+1} is correct,
   but its final simplification to F((1/2)S_n) = 5·3^n·R_n + 1 is not.
   At n=1 that formula gives 16; the paper's own unsimplified expression
   ½(2s_n + s_{n+1} - s_0) = ½(88+134-14) gives 104, and 104 is correct.
   At n=2: formula gives 181, correct value is 989.
   Correct closed form: F = (25·3^(2n) - 5·3^n - 2)/2.
   (The companion genus result, Example 6.2, IS correct.) -/
theorem linrec_ex52_2_n1_TRUE :
    frobeniusNumber [7, 22, 67, 202] = 104 := by native_decide

theorem linrec_ex52_2_n2_TRUE :
    frobeniusNumber [22, 67, 202, 607, 1822] = 989 := by native_decide

-- Example 6.2 genus for the same family, n=1: g = ½(5n+6+25R_n)·3^n = 54.
theorem linrec_ex62_genus : genusApery [7, 22, 67, 202] = 54 := by native_decide

-- Family x_n = (2^k - 1)·2^n - 1 with k > 2^n (§5, explicitly noted as
-- not treated in the earlier literature). n=1, k=3.
-- F = 2^(2n+2k) - 2^(2n+k) - 2^(n+k) - 1 = 256 - 32 - 16 - 1 = 207.
theorem linrec_pow2_kGt : frobeniusNumber [13, 27, 55, 111] = 207 := by native_decide

-- Family x_n = (a^k - 1)·a^n - 1, a ≥ 3. Case k=1, n=1 (a=3):
-- F = a^5 - 3a^4 + 2a^3 - a^2 + 3 = 243 - 243 + 54 - 9 + 3 = 48.
theorem linrec_k1_n1 : frobeniusNumber [5, 17, 53] = 48 := by native_decide

-- Same family, case k=1, n>1 (a=3, n=2).
theorem linrec_k1_nGt1 : frobeniusNumber [17, 53, 161, 485] = 627 := by native_decide

-- Same family, case n=1, k>1, k ≤ a+1 (a=3, k=2).
theorem linrec_n1_kSmall : frobeniusNumber [23, 71, 215, 647] = 1125 := by native_decide

-- Same family, case n=1, k>1, k > a+1 (a=3, k=5; threshold a+1=4).
theorem linrec_n1_kLarge :
    frobeniusNumber [725, 2177, 6533, 19601, 58805, 176417, 529253]
      = 1057773 := by native_decide

/- Same family, case n>1, k≥2, sub-case 0 ≤ k-2 < (a-1)R_n.
   The paper gives max Ap symbolically but EXPLICITLY DECLINES to simplify
   F ("we do not write down explicitly"), so there is no published closed
   form to audit here — this theorem records the actual value instead.
   a=3, n=2, k=5 (R_n=4, threshold 8, k-2=3). -/
theorem linrec_nGt1_kSmall_NOFORMULA :
    frobeniusNumber [2177, 6533, 19601, 58805, 176417, 529253, 1587761, 4763285]
      = 9504780 := by native_decide

/- ⚠ DISCREPANCY — same family, sub-case n>1, k≥2, k-2 ≥ (a-1)R_n.
   Printed formula:
     F = a^(2n+2k+1) - a^(2n+2k) - a^(2n+k+1) - a^(2n+k)
         - a^(n+k) - a^(n+1) + 2a^n - 2a + 3
   For a=3, n=2, k=10 this gives 564839409633, but the true value is
   564848975571 — short by exactly 2·a^(n+k+2) = 2·3^14 = 9565938. Same
   exact offset at k=11 (2·3^15) and k=12 (2·3^16), so it's a systematic
   missing term, not a rounding artifact. Correct formula adds +2a^(n+k+2).

   NOTE: this is the slow one — smallest generator is 531431, so expect
   this single theorem to take minutes under native_decide. Comment it out
   if you want a fast build; every other theorem here is quick. -/
 /-theorem linrec_nGt1_kLarge_TRUE :
    frobeniusNumber [531431, 1594295, 4782887, 14348663, 43045991, 129137975,
      387413927, 1162241783, 3486725351, 10460176055, 31380528167,
      94141584503, 282424753511] = 564848975571 := by
  native_decide -/


/- ═══════════════════════════════════════════════════════════════════
   PAPER 6 — The Frobenius number of geometric sequences
   Ong & Ponomarenko, INTEGERS: Elec. J. Combin. Number Theory
   (https://vadim.sdsu.edu/op.pdf)
   Generators {m^k, m^(k-1)n, ..., n^k} for gcd(m,n) = 1. SINGLE theorem,
   no case split:
     g = n^(k-1)(mn - m - n) + (n-1)m²(m^(k-1) - n^(k-1))/(m - n).
   Paper states no numerical examples; all instances constructed.
   ═══════════════════════════════════════════════════════════════════ -/

-- k = 1 base case: reduces exactly to Sylvester (mn - m - n). m=2, n=3.
theorem geom_k1 : frobeniusNumber [2, 3] = 1 := by native_decide

-- k = 2, m=2, n=3: g = 3·1 + 2·4·(2-3)/(2-3) = 3 + 8 = 11.
theorem geom_k2 : frobeniusNumber [4, 6, 9] = 11 := by native_decide

-- k = 3, m=2, n=3: g = 9·1 + 2·4·(4-9)/(2-3) = 9 + 40 = 49.
theorem geom_k3 : frobeniusNumber [8, 12, 18, 27] = 49 := by native_decide

-- k = 2, m=2, n=5 (larger ratio): g = 5·3 + 4·4·(2-5)/(2-5) = 15 + 16 = 31.
theorem geom_k2_alt : frobeniusNumber [4, 10, 25] = 31 := by native_decide

-- Symmetry check: swapping m and n gives the same generator SET, so the
-- formula must agree. m=3, n=2, k=2 → {9,6,4}, same as geom_k2 above.
theorem geom_swap : frobeniusNumber [9, 6, 4] = 11 := by native_decide


/- ═══════════════════════════════════════════════════════════════════
   PAPER 7 — Triangular and tetrahedral number sequences
   arXiv:1706.04378 (Robles-Pérez & Rosales), J. Number Theory 186 (2018).
   T_n = n(n+1)/2 (three consecutive, §2); TH_n = n(n+1)(n+2)/6 (four
   consecutive, §3). Validity: triangular n ≥ 3, tetrahedral n ≥ 4
   (Lemma 15). Eight cases total.
   ═══════════════════════════════════════════════════════════════════ -/

/- Case 1 — triangular, n ODD (Proposition 6): F = (3n³+6n²-3n-10)/4.
   n = 3 → ⟨6,10,15⟩. Note: gcd(6,10)=2, gcd(6,15)=3, gcd(10,15)=5, so NO
   pair here is individually coprime even though gcd of all three is 1.
   Harmless for the Apéry core (bounded by smallest generator, not by any
   coprime pair), but it's exactly the case that used to force the old
   core down its constructCoprimePartner fallback path. -/
theorem tri_odd_n3 : frobeniusNumber [6, 10, 15] = 29 := by native_decide

-- Case 2 — triangular, n EVEN (Proposition 6): F = (3n³+9n²+6n-4)/4. n=4.
theorem tri_even_n4 : frobeniusNumber [10, 15, 21] = 89 := by native_decide

-- Case 3 — tetrahedral, n ≡ 0 (mod 6) (Proposition 12.1). n = 6.
theorem tet_n0mod6 : frobeniusNumber [56, 84, 120, 165] = 1243 := by native_decide

/- Case 4 — tetrahedral, n ≡ 1 (mod 6) (Proposition 12.2). n = 7.
   Second pairwise-non-coprime case: gcds are 12, 3, 4, 15, 20, 55 — again
   no individually coprime pair. -/
theorem tet_n1mod6 : frobeniusNumber [84, 120, 165, 220] = 1571 := by native_decide

-- Case 5 — tetrahedral, n ≡ 2 (mod 6) (Proposition 12.3). n = 8.
theorem tet_n2mod6 : frobeniusNumber [120, 165, 220, 286] = 2619 := by native_decide

-- Case 6 — tetrahedral, n ≡ 3 (mod 6) (Proposition 12.4). n = 9.
theorem tet_n3mod6 : frobeniusNumber [165, 220, 286, 364] = 5059 := by native_decide

-- Case 7 — tetrahedral, n ≡ 4 (mod 6) (Proposition 12.5). REVERSE
-- telescopic order (Proposition 11). n = 4.
theorem tet_n4mod6 : frobeniusNumber [20, 35, 56, 84] = 253 := by native_decide

-- Case 8 — tetrahedral, n ≡ 5 (mod 6) (Proposition 12.6). Also reverse
-- telescopic order. n = 5.
theorem tet_n5mod6 : frobeniusNumber [35, 56, 84, 120] = 853 := by native_decide

/- NOT FORMALIZABLE from this paper: Remark 13 sketches a 5-term family
   C(n,4),...,C(n+4,4) as telescopic for certain residues mod 12 but gives
   no closed form (left as future work); Remark 14 notes 6-term families
   with m=5 are not telescopic under ANY permutation, so the method does
   not extend. Genus is not a theorem target of this paper at all. -/


/- ═══════════════════════════════════════════════════════════════════
   PAPER 8 — Frobenius number of squares
   arXiv:2507.01898 (Robles-Pérez & Rosales). Despite the project-overview
   shorthand "squares of a semigroup", the actual construction is narrower:
   S(n) = ⟨f_n², f_{n+1}², f_{n+2}²⟩ for three CONSECUTIVE FIBONACCI
   numbers. Three cases by parity (equivalently n mod 3), valid n ≥ 4.
   Authoritative source is Theorem 5.15 / Corollary 5.16 (§5, fully
   proved); §3 and §4 give parallel derivations the authors themselves
   leave as unproven "Claims", so don't audit against those.
   The paper gives NO genus formula anywhere.
   ═══════════════════════════════════════════════════════════════════ -/

-- Case 1 — f_n even, n ≡ 0 (mod 3), n ≥ 6 (Cor. 5.16.1).
-- n=6: ⟨8,13,21⟩ squared. Paper's own Example 5.17.3.
theorem sqfib_case1_n6 : frobeniusNumber [64, 169, 441] = 3522 := by native_decide

-- Case 2 — f_{n+1} even, n ≡ 2 (mod 3), n ≥ 5 (Cor. 5.16.2).
-- n=5: ⟨5,8,13⟩ squared. Paper's own Example 5.17.2.
theorem sqfib_case2_n5 : frobeniusNumber [25, 64, 169] = 743 := by native_decide

-- Case 3 — f_{n+2} even, n ≡ 1 (mod 3), n ≥ 4 (Cor. 5.16.3).
-- n=4: ⟨3,5,8⟩ squared. Paper's own Example 5.17.1.
theorem sqfib_case3_n4 : frobeniusNumber [9, 25, 64] = 130 := by native_decide

-- Degenerate boundary case the paper calls out separately: S(3) = ⟨4,9,25⟩
-- collapses to ⟨4,9⟩ (embedding dimension drops to 2), so Sylvester
-- applies: 4·9 - 4 - 9 = 23. Outside the three-case split above.
theorem sqfib_degenerate_n3 : frobeniusNumber [4, 9, 25] = 23 := by native_decide
